// Brand → website domain map for common Indian construction / finishing makes.
// Logos are hotlinked from Clearbit's public logo endpoint, so no assets are
// stored in the project. Unknown brands fall back to an initials badge.
const BRAND_DOMAINS: Record<string, string> = {
  kohler: "kohler.com",
  jaquar: "jaquar.com",
  hindware: "hindware.com",
  cera: "cera-india.com",
  parryware: "parryware.in",
  grohe: "grohe.in",
  toto: "toto.com",
  duravit: "duravit.in",
  roca: "roca.com",
  "american standard": "americanstandard.co.in",
  ultratech: "ultratechcement.com",
  acc: "acclimited.com",
  ambuja: "ambujacement.com",
  dalmia: "dalmiacement.com",
  ramco: "ramcocements.in",
  "birla a1": "birlaa1.com",
  tata: "tatasteel.com",
  "tata tiscon": "tatasteel.com",
  jsw: "jsw.in",
  sail: "sail.co.in",
  vizag: "vizagsteel.com",
  kamdhenu: "kamdhenulimited.com",
  "asian paints": "asianpaints.com",
  berger: "bergerpaints.com",
  nerolac: "nerolac.com",
  dulux: "dulux.in",
  "birla opus": "birlaopus.com",
  jotun: "jotun.com",
  indigo: "indigopaints.com",
  finolex: "finolex.com",
  polycab: "polycab.com",
  havells: "havells.com",
  "rr kabel": "rrkabel.com",
  anchor: "anchor-world.com",
  legrand: "legrand.co.in",
  schneider: "se.com",
  siemens: "siemens.com",
  abb: "abb.com",
  crompton: "crompton.co.in",
  philips: "philips.co.in",
  wipro: "wiprolighting.com",
  syska: "syska.co.in",
  supreme: "supreme.co.in",
  astral: "astralpipes.com",
  ashirvad: "ashirvad.com",
  prince: "princepipes.com",
  "captain pipes": "captainpipes.com",
  kisan: "kisangroup.com",
  kajaria: "kajariaceramics.com",
  somany: "somanyceramics.com",
  johnson: "hrjohnsonindia.com",
  nitco: "nitco.in",
  orientbell: "orientbell.com",
  simpolo: "simpolo.com",
  varmora: "varmora.com",
  asianGranito: "aglasiangranito.com",
  "greenply": "greenply.com",
  "century ply": "centuryply.com",
  merino: "merinolaminates.com",
  "fundermax": "fundermax.com",
  saint: "saint-gobain.co.in",
  "saint-gobain": "saint-gobain.co.in",
  "saint gobain": "saint-gobain.co.in",
  fenesta: "fenesta.com",
  aluplast: "aluplast.net",
  encraft: "encraftindia.com",
  gypsteel: "gyproc.in",
  gyproc: "gyproc.in",
  armstrong: "armstrongceilings.com",
  dr_fixit: "drfixit.co.in",
  "dr fixit": "drfixit.co.in",
  "dr. fixit": "drfixit.co.in",
  fosroc: "fosroc.com",
  sika: "sika.com",
  mapei: "mapei.com",
  bostik: "bostik.com",
  pidilite: "pidilite.com",
  fevicol: "pidilite.com",
  roff: "roff.in",
  laticrete: "laticrete.com",
  ardex: "ardexendura.com",
  hettich: "hettich.com",
  hafele: "hafeleindia.com",
  blum: "blum.com",
  godrej: "godrej.com",
  yale: "yalehome.co.in",
  dorma: "dormakabaindia.com",
  kone: "kone.in",
  otis: "otis.com",
  schindler: "schindler.co.in",
  johnsonlifts: "johnsonliftsltd.com",
  thyssenkrupp: "tkelevator.com",
  "v-guard": "vguard.in",
  aquaguard: "eurekaforbes.com",
  cpvc: "astralpipes.com",
  ksb: "ksb.com",
  kirloskar: "kirloskarpumps.com",
  grundfos: "grundfos.com",
  lubi: "lubipumps.com",
  daikin: "daikinindia.com",
  bluestar: "bluestarindia.com",
  voltas: "voltas.com",
  hitachi: "hitachiaircon.in",
  mitsubishi: "mitsubishielectric.in",
  cummins: "cummins.com",
  kirloskarGreen: "koel.kirloskar.com",
  ashok: "ashokleyland.com",
};

export function brandLogoUrl(brand: string): string | null {
  const key = (brand || "").trim().toLowerCase();
  if (!key) return null;
  const hit =
    BRAND_DOMAINS[key] ??
    Object.entries(BRAND_DOMAINS).find(([name]) => key.includes(name))?.[1] ??
    null;
  return hit ? `https://logo.clearbit.com/${hit}` : null;
}
