// Screens that still render illustrative/reference figures instead of live
// project data. Remove a path from this list once that screen is wired to
// site_projects / boq_items and shows real numbers (or an empty state).
export const SAMPLE_DATA_ROUTES: Record<string, string> = {
  "/qa": "QA gates, defect counts and inspection history",
  "/qa-inspection": "inspection checklists and pass/fail counts",
  "/pour-cards": "pour card schedule and approvals",
  "/procurement": "procurement pipeline and vendor quotes",
  "/purchasing-center": "purchase requests and order values",
  "/price-intelligence": "mandi / market rate feeds",
  "/brand-benchmark": "brand comparison rates",
  "/tender-comparison": "tender bids and comparisons",
  "/field-console": "biometric attendance and field activity counts",
  "/contractors-labour": "labour headcount and productivity",
  "/inventory-control": "stock levels and consumption",
  "/site-execution": "stage progress, workforce and material runway",
  "/execution-manual": "QA/QC stage metrics and lifecycle status",
  "/command-operations": "operational activity feed and metrics",
  "/project-controls": "schedule and cost control indices",
  "/financial-forecast": "cashflow forecast figures",
  "/financial-ingestion": "ingested invoice and ledger samples",
  "/billing-expenditure": "billing and expenditure figures",
  "/bills-payments": "bill and payment records",
  "/capital-ledger": "capital ledger entries",
  "/landowners-investment": "investor payout schedules",
  "/vendor-lifecycle": "vendor scores and lifecycle stages",
  "/vendor-directory": "vendor directory records",
  "/drawing-decipher": "drawing takeoff results",
  "/media-upload-studio": "uploaded media samples",
  "/site-media": "site media samples",
  "/scope-brief": "scope brief content",
  "/pmc-scope": "PMC scope items",
  "/ai-programme": "programme schedule sample",
  "/system-directory": "directory records",
  "/boq-upload": "sample BOQ upload rows",
  "/roles-access": "sample role assignments",
};
