/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiProgrammeRouteImport } from './routes/ai-programme'
import { Route as BillingExpenditureRouteImport } from './routes/billing-expenditure'
import { Route as BillsPaymentsRouteImport } from './routes/bills-payments'
import { Route as BoqRouteImport } from './routes/boq'
import { Route as BoqEngineRouteImport } from './routes/boq-engine'
import { Route as BoqUploadRouteImport } from './routes/boq-upload'
import { Route as BrandBenchmarkRouteImport } from './routes/brand-benchmark'
import { Route as CapitalLedgerRouteImport } from './routes/capital-ledger'
import { Route as CommandOperationsRouteImport } from './routes/command-operations'
import { Route as ContractorsLabourRouteImport } from './routes/contractors-labour'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DrawingDecipherRouteImport } from './routes/drawing-decipher'
import { Route as ExecutionManualRouteImport } from './routes/execution-manual'
import { Route as FieldConsoleRouteImport } from './routes/field-console'
import { Route as FinancialForecastRouteImport } from './routes/financial-forecast'
import { Route as FinancialIngestionRouteImport } from './routes/financial-ingestion'
import { Route as InventoryControlRouteImport } from './routes/inventory-control'
import { Route as LandownersInvestmentRouteImport } from './routes/landowners-investment'
import { Route as MediaUploadStudioRouteImport } from './routes/media-upload-studio'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PmcScopeRouteImport } from './routes/pmc-scope'
import { Route as PoCreateRouteImport } from './routes/po-create'
import { Route as PourCardsRouteImport } from './routes/pour-cards'
import { Route as PriceIntelligenceRouteImport } from './routes/price-intelligence'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as ProjectControlsRouteImport } from './routes/project-controls'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProjectsSetupRouteImport } from './routes/projects-setup'
import { Route as PurchaseOrdersRouteImport } from './routes/purchase-orders'
import { Route as PurchasingCenterRouteImport } from './routes/purchasing-center'
import { Route as QaRouteImport } from './routes/qa'
import { Route as QaInspectionRouteImport } from './routes/qa-inspection'
import { Route as RolesAccessRouteImport } from './routes/roles-access'
import { Route as ScopeBriefRouteImport } from './routes/scope-brief'
import { Route as SiteExecutionRouteImport } from './routes/site-execution'
import { Route as SiteMediaRouteImport } from './routes/site-media'
import { Route as SystemDirectoryRouteImport } from './routes/system-directory'
import { Route as TenderComparisonRouteImport } from './routes/tender-comparison'
import { Route as VendorDirectoryRouteImport } from './routes/vendor-directory'
import { Route as VendorLifecycleRouteImport } from './routes/vendor-lifecycle'
import { Route as AiIndexRouteImport } from './routes/ai.index'
import { Route as AiThreadIdRouteImport } from './routes/ai.$threadId'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiProgrammeRoute = AiProgrammeRouteImport.update({
  id: '/ai-programme',
  path: '/ai-programme',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingExpenditureRoute = BillingExpenditureRouteImport.update({
  id: '/billing-expenditure',
  path: '/billing-expenditure',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsPaymentsRoute = BillsPaymentsRouteImport.update({
  id: '/bills-payments',
  path: '/bills-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const BoqRoute = BoqRouteImport.update({
  id: '/boq',
  path: '/boq',
  getParentRoute: () => rootRouteImport,
} as any)
const BoqEngineRoute = BoqEngineRouteImport.update({
  id: '/boq-engine',
  path: '/boq-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const BoqUploadRoute = BoqUploadRouteImport.update({
  id: '/boq-upload',
  path: '/boq-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandBenchmarkRoute = BrandBenchmarkRouteImport.update({
  id: '/brand-benchmark',
  path: '/brand-benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const CapitalLedgerRoute = CapitalLedgerRouteImport.update({
  id: '/capital-ledger',
  path: '/capital-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandOperationsRoute = CommandOperationsRouteImport.update({
  id: '/command-operations',
  path: '/command-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorsLabourRoute = ContractorsLabourRouteImport.update({
  id: '/contractors-labour',
  path: '/contractors-labour',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingDecipherRoute = DrawingDecipherRouteImport.update({
  id: '/drawing-decipher',
  path: '/drawing-decipher',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionManualRoute = ExecutionManualRouteImport.update({
  id: '/execution-manual',
  path: '/execution-manual',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldConsoleRoute = FieldConsoleRouteImport.update({
  id: '/field-console',
  path: '/field-console',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialForecastRoute = FinancialForecastRouteImport.update({
  id: '/financial-forecast',
  path: '/financial-forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialIngestionRoute = FinancialIngestionRouteImport.update({
  id: '/financial-ingestion',
  path: '/financial-ingestion',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryControlRoute = InventoryControlRouteImport.update({
  id: '/inventory-control',
  path: '/inventory-control',
  getParentRoute: () => rootRouteImport,
} as any)
const LandownersInvestmentRoute = LandownersInvestmentRouteImport.update({
  id: '/landowners-investment',
  path: '/landowners-investment',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaUploadStudioRoute = MediaUploadStudioRouteImport.update({
  id: '/media-upload-studio',
  path: '/media-upload-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PmcScopeRoute = PmcScopeRouteImport.update({
  id: '/pmc-scope',
  path: '/pmc-scope',
  getParentRoute: () => rootRouteImport,
} as any)
const PoCreateRoute = PoCreateRouteImport.update({
  id: '/po-create',
  path: '/po-create',
  getParentRoute: () => rootRouteImport,
} as any)
const PourCardsRoute = PourCardsRouteImport.update({
  id: '/pour-cards',
  path: '/pour-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceIntelligenceRoute = PriceIntelligenceRouteImport.update({
  id: '/price-intelligence',
  path: '/price-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectControlsRoute = ProjectControlsRouteImport.update({
  id: '/project-controls',
  path: '/project-controls',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSetupRoute = ProjectsSetupRouteImport.update({
  id: '/projects-setup',
  path: '/projects-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersRoute = PurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasingCenterRoute = PurchasingCenterRouteImport.update({
  id: '/purchasing-center',
  path: '/purchasing-center',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const QaInspectionRoute = QaInspectionRouteImport.update({
  id: '/qa-inspection',
  path: '/qa-inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesAccessRoute = RolesAccessRouteImport.update({
  id: '/roles-access',
  path: '/roles-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopeBriefRoute = ScopeBriefRouteImport.update({
  id: '/scope-brief',
  path: '/scope-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteExecutionRoute = SiteExecutionRouteImport.update({
  id: '/site-execution',
  path: '/site-execution',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteMediaRoute = SiteMediaRouteImport.update({
  id: '/site-media',
  path: '/site-media',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemDirectoryRoute = SystemDirectoryRouteImport.update({
  id: '/system-directory',
  path: '/system-directory',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderComparisonRoute = TenderComparisonRouteImport.update({
  id: '/tender-comparison',
  path: '/tender-comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDirectoryRoute = VendorDirectoryRouteImport.update({
  id: '/vendor-directory',
  path: '/vendor-directory',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorLifecycleRoute = VendorLifecycleRouteImport.update({
  id: '/vendor-lifecycle',
  path: '/vendor-lifecycle',
  getParentRoute: () => rootRouteImport,
} as any)
const AiIndexRoute = AiIndexRouteImport.update({
  id: '/ai/',
  path: '/ai/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiThreadIdRoute = AiThreadIdRouteImport.update({
  id: '/ai/$threadId',
  path: '/ai/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-programme': typeof AiProgrammeRoute
  '/billing-expenditure': typeof BillingExpenditureRoute
  '/bills-payments': typeof BillsPaymentsRoute
  '/boq': typeof BoqRoute
  '/boq-engine': typeof BoqEngineRoute
  '/boq-upload': typeof BoqUploadRoute
  '/brand-benchmark': typeof BrandBenchmarkRoute
  '/capital-ledger': typeof CapitalLedgerRoute
  '/command-operations': typeof CommandOperationsRoute
  '/contractors-labour': typeof ContractorsLabourRoute
  '/dashboard': typeof DashboardRoute
  '/drawing-decipher': typeof DrawingDecipherRoute
  '/execution-manual': typeof ExecutionManualRoute
  '/field-console': typeof FieldConsoleRoute
  '/financial-forecast': typeof FinancialForecastRoute
  '/financial-ingestion': typeof FinancialIngestionRoute
  '/inventory-control': typeof InventoryControlRoute
  '/landowners-investment': typeof LandownersInvestmentRoute
  '/media-upload-studio': typeof MediaUploadStudioRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/pmc-scope': typeof PmcScopeRoute
  '/po-create': typeof PoCreateRoute
  '/pour-cards': typeof PourCardsRoute
  '/price-intelligence': typeof PriceIntelligenceRoute
  '/procurement': typeof ProcurementRoute
  '/project-controls': typeof ProjectControlsRoute
  '/projects': typeof ProjectsRoute
  '/projects-setup': typeof ProjectsSetupRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/purchasing-center': typeof PurchasingCenterRoute
  '/qa': typeof QaRoute
  '/qa-inspection': typeof QaInspectionRoute
  '/roles-access': typeof RolesAccessRoute
  '/scope-brief': typeof ScopeBriefRoute
  '/site-execution': typeof SiteExecutionRoute
  '/site-media': typeof SiteMediaRoute
  '/system-directory': typeof SystemDirectoryRoute
  '/tender-comparison': typeof TenderComparisonRoute
  '/vendor-directory': typeof VendorDirectoryRoute
  '/vendor-lifecycle': typeof VendorLifecycleRoute
  '/ai/$threadId': typeof AiThreadIdRoute
  '/api/chat': typeof ApiChatRoute
  '/ai/': typeof AiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-programme': typeof AiProgrammeRoute
  '/billing-expenditure': typeof BillingExpenditureRoute
  '/bills-payments': typeof BillsPaymentsRoute
  '/boq': typeof BoqRoute
  '/boq-engine': typeof BoqEngineRoute
  '/boq-upload': typeof BoqUploadRoute
  '/brand-benchmark': typeof BrandBenchmarkRoute
  '/capital-ledger': typeof CapitalLedgerRoute
  '/command-operations': typeof CommandOperationsRoute
  '/contractors-labour': typeof ContractorsLabourRoute
  '/dashboard': typeof DashboardRoute
  '/drawing-decipher': typeof DrawingDecipherRoute
  '/execution-manual': typeof ExecutionManualRoute
  '/field-console': typeof FieldConsoleRoute
  '/financial-forecast': typeof FinancialForecastRoute
  '/financial-ingestion': typeof FinancialIngestionRoute
  '/inventory-control': typeof InventoryControlRoute
  '/landowners-investment': typeof LandownersInvestmentRoute
  '/media-upload-studio': typeof MediaUploadStudioRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/pmc-scope': typeof PmcScopeRoute
  '/po-create': typeof PoCreateRoute
  '/pour-cards': typeof PourCardsRoute
  '/price-intelligence': typeof PriceIntelligenceRoute
  '/procurement': typeof ProcurementRoute
  '/project-controls': typeof ProjectControlsRoute
  '/projects': typeof ProjectsRoute
  '/projects-setup': typeof ProjectsSetupRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/purchasing-center': typeof PurchasingCenterRoute
  '/qa': typeof QaRoute
  '/qa-inspection': typeof QaInspectionRoute
  '/roles-access': typeof RolesAccessRoute
  '/scope-brief': typeof ScopeBriefRoute
  '/site-execution': typeof SiteExecutionRoute
  '/site-media': typeof SiteMediaRoute
  '/system-directory': typeof SystemDirectoryRoute
  '/tender-comparison': typeof TenderComparisonRoute
  '/vendor-directory': typeof VendorDirectoryRoute
  '/vendor-lifecycle': typeof VendorLifecycleRoute
  '/ai/$threadId': typeof AiThreadIdRoute
  '/api/chat': typeof ApiChatRoute
  '/ai': typeof AiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-programme': typeof AiProgrammeRoute
  '/billing-expenditure': typeof BillingExpenditureRoute
  '/bills-payments': typeof BillsPaymentsRoute
  '/boq': typeof BoqRoute
  '/boq-engine': typeof BoqEngineRoute
  '/boq-upload': typeof BoqUploadRoute
  '/brand-benchmark': typeof BrandBenchmarkRoute
  '/capital-ledger': typeof CapitalLedgerRoute
  '/command-operations': typeof CommandOperationsRoute
  '/contractors-labour': typeof ContractorsLabourRoute
  '/dashboard': typeof DashboardRoute
  '/drawing-decipher': typeof DrawingDecipherRoute
  '/execution-manual': typeof ExecutionManualRoute
  '/field-console': typeof FieldConsoleRoute
  '/financial-forecast': typeof FinancialForecastRoute
  '/financial-ingestion': typeof FinancialIngestionRoute
  '/inventory-control': typeof InventoryControlRoute
  '/landowners-investment': typeof LandownersInvestmentRoute
  '/media-upload-studio': typeof MediaUploadStudioRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/pmc-scope': typeof PmcScopeRoute
  '/po-create': typeof PoCreateRoute
  '/pour-cards': typeof PourCardsRoute
  '/price-intelligence': typeof PriceIntelligenceRoute
  '/procurement': typeof ProcurementRoute
  '/project-controls': typeof ProjectControlsRoute
  '/projects': typeof ProjectsRoute
  '/projects-setup': typeof ProjectsSetupRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/purchasing-center': typeof PurchasingCenterRoute
  '/qa': typeof QaRoute
  '/qa-inspection': typeof QaInspectionRoute
  '/roles-access': typeof RolesAccessRoute
  '/scope-brief': typeof ScopeBriefRoute
  '/site-execution': typeof SiteExecutionRoute
  '/site-media': typeof SiteMediaRoute
  '/system-directory': typeof SystemDirectoryRoute
  '/tender-comparison': typeof TenderComparisonRoute
  '/vendor-directory': typeof VendorDirectoryRoute
  '/vendor-lifecycle': typeof VendorLifecycleRoute
  '/ai/$threadId': typeof AiThreadIdRoute
  '/api/chat': typeof ApiChatRoute
  '/ai/': typeof AiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-programme'
    | '/billing-expenditure'
    | '/bills-payments'
    | '/boq'
    | '/boq-engine'
    | '/boq-upload'
    | '/brand-benchmark'
    | '/capital-ledger'
    | '/command-operations'
    | '/contractors-labour'
    | '/dashboard'
    | '/drawing-decipher'
    | '/execution-manual'
    | '/field-console'
    | '/financial-forecast'
    | '/financial-ingestion'
    | '/inventory-control'
    | '/landowners-investment'
    | '/media-upload-studio'
    | '/messages'
    | '/notifications'
    | '/pmc-scope'
    | '/po-create'
    | '/pour-cards'
    | '/price-intelligence'
    | '/procurement'
    | '/project-controls'
    | '/projects'
    | '/projects-setup'
    | '/purchase-orders'
    | '/purchasing-center'
    | '/qa'
    | '/qa-inspection'
    | '/roles-access'
    | '/scope-brief'
    | '/site-execution'
    | '/site-media'
    | '/system-directory'
    | '/tender-comparison'
    | '/vendor-directory'
    | '/vendor-lifecycle'
    | '/ai/$threadId'
    | '/api/chat'
    | '/ai/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-programme'
    | '/billing-expenditure'
    | '/bills-payments'
    | '/boq'
    | '/boq-engine'
    | '/boq-upload'
    | '/brand-benchmark'
    | '/capital-ledger'
    | '/command-operations'
    | '/contractors-labour'
    | '/dashboard'
    | '/drawing-decipher'
    | '/execution-manual'
    | '/field-console'
    | '/financial-forecast'
    | '/financial-ingestion'
    | '/inventory-control'
    | '/landowners-investment'
    | '/media-upload-studio'
    | '/messages'
    | '/notifications'
    | '/pmc-scope'
    | '/po-create'
    | '/pour-cards'
    | '/price-intelligence'
    | '/procurement'
    | '/project-controls'
    | '/projects'
    | '/projects-setup'
    | '/purchase-orders'
    | '/purchasing-center'
    | '/qa'
    | '/qa-inspection'
    | '/roles-access'
    | '/scope-brief'
    | '/site-execution'
    | '/site-media'
    | '/system-directory'
    | '/tender-comparison'
    | '/vendor-directory'
    | '/vendor-lifecycle'
    | '/ai/$threadId'
    | '/api/chat'
    | '/ai'
  id:
    | '__root__'
    | '/'
    | '/ai-programme'
    | '/billing-expenditure'
    | '/bills-payments'
    | '/boq'
    | '/boq-engine'
    | '/boq-upload'
    | '/brand-benchmark'
    | '/capital-ledger'
    | '/command-operations'
    | '/contractors-labour'
    | '/dashboard'
    | '/drawing-decipher'
    | '/execution-manual'
    | '/field-console'
    | '/financial-forecast'
    | '/financial-ingestion'
    | '/inventory-control'
    | '/landowners-investment'
    | '/media-upload-studio'
    | '/messages'
    | '/notifications'
    | '/pmc-scope'
    | '/po-create'
    | '/pour-cards'
    | '/price-intelligence'
    | '/procurement'
    | '/project-controls'
    | '/projects'
    | '/projects-setup'
    | '/purchase-orders'
    | '/purchasing-center'
    | '/qa'
    | '/qa-inspection'
    | '/roles-access'
    | '/scope-brief'
    | '/site-execution'
    | '/site-media'
    | '/system-directory'
    | '/tender-comparison'
    | '/vendor-directory'
    | '/vendor-lifecycle'
    | '/ai/$threadId'
    | '/api/chat'
    | '/ai/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiProgrammeRoute: typeof AiProgrammeRoute
  BillingExpenditureRoute: typeof BillingExpenditureRoute
  BillsPaymentsRoute: typeof BillsPaymentsRoute
  BoqRoute: typeof BoqRoute
  BoqEngineRoute: typeof BoqEngineRoute
  BoqUploadRoute: typeof BoqUploadRoute
  BrandBenchmarkRoute: typeof BrandBenchmarkRoute
  CapitalLedgerRoute: typeof CapitalLedgerRoute
  CommandOperationsRoute: typeof CommandOperationsRoute
  ContractorsLabourRoute: typeof ContractorsLabourRoute
  DashboardRoute: typeof DashboardRoute
  DrawingDecipherRoute: typeof DrawingDecipherRoute
  ExecutionManualRoute: typeof ExecutionManualRoute
  FieldConsoleRoute: typeof FieldConsoleRoute
  FinancialForecastRoute: typeof FinancialForecastRoute
  FinancialIngestionRoute: typeof FinancialIngestionRoute
  InventoryControlRoute: typeof InventoryControlRoute
  LandownersInvestmentRoute: typeof LandownersInvestmentRoute
  MediaUploadStudioRoute: typeof MediaUploadStudioRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  PmcScopeRoute: typeof PmcScopeRoute
  PoCreateRoute: typeof PoCreateRoute
  PourCardsRoute: typeof PourCardsRoute
  PriceIntelligenceRoute: typeof PriceIntelligenceRoute
  ProcurementRoute: typeof ProcurementRoute
  ProjectControlsRoute: typeof ProjectControlsRoute
  ProjectsRoute: typeof ProjectsRoute
  ProjectsSetupRoute: typeof ProjectsSetupRoute
  PurchaseOrdersRoute: typeof PurchaseOrdersRoute
  PurchasingCenterRoute: typeof PurchasingCenterRoute
  QaRoute: typeof QaRoute
  QaInspectionRoute: typeof QaInspectionRoute
  RolesAccessRoute: typeof RolesAccessRoute
  ScopeBriefRoute: typeof ScopeBriefRoute
  SiteExecutionRoute: typeof SiteExecutionRoute
  SiteMediaRoute: typeof SiteMediaRoute
  SystemDirectoryRoute: typeof SystemDirectoryRoute
  TenderComparisonRoute: typeof TenderComparisonRoute
  VendorDirectoryRoute: typeof VendorDirectoryRoute
  VendorLifecycleRoute: typeof VendorLifecycleRoute
  AiThreadIdRoute: typeof AiThreadIdRoute
  ApiChatRoute: typeof ApiChatRoute
  AiIndexRoute: typeof AiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-programme': {
      id: '/ai-programme'
      path: '/ai-programme'
      fullPath: '/ai-programme'
      preLoaderRoute: typeof AiProgrammeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing-expenditure': {
      id: '/billing-expenditure'
      path: '/billing-expenditure'
      fullPath: '/billing-expenditure'
      preLoaderRoute: typeof BillingExpenditureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills-payments': {
      id: '/bills-payments'
      path: '/bills-payments'
      fullPath: '/bills-payments'
      preLoaderRoute: typeof BillsPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boq': {
      id: '/boq'
      path: '/boq'
      fullPath: '/boq'
      preLoaderRoute: typeof BoqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boq-engine': {
      id: '/boq-engine'
      path: '/boq-engine'
      fullPath: '/boq-engine'
      preLoaderRoute: typeof BoqEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boq-upload': {
      id: '/boq-upload'
      path: '/boq-upload'
      fullPath: '/boq-upload'
      preLoaderRoute: typeof BoqUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-benchmark': {
      id: '/brand-benchmark'
      path: '/brand-benchmark'
      fullPath: '/brand-benchmark'
      preLoaderRoute: typeof BrandBenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capital-ledger': {
      id: '/capital-ledger'
      path: '/capital-ledger'
      fullPath: '/capital-ledger'
      preLoaderRoute: typeof CapitalLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-operations': {
      id: '/command-operations'
      path: '/command-operations'
      fullPath: '/command-operations'
      preLoaderRoute: typeof CommandOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractors-labour': {
      id: '/contractors-labour'
      path: '/contractors-labour'
      fullPath: '/contractors-labour'
      preLoaderRoute: typeof ContractorsLabourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawing-decipher': {
      id: '/drawing-decipher'
      path: '/drawing-decipher'
      fullPath: '/drawing-decipher'
      preLoaderRoute: typeof DrawingDecipherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execution-manual': {
      id: '/execution-manual'
      path: '/execution-manual'
      fullPath: '/execution-manual'
      preLoaderRoute: typeof ExecutionManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-console': {
      id: '/field-console'
      path: '/field-console'
      fullPath: '/field-console'
      preLoaderRoute: typeof FieldConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-forecast': {
      id: '/financial-forecast'
      path: '/financial-forecast'
      fullPath: '/financial-forecast'
      preLoaderRoute: typeof FinancialForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-ingestion': {
      id: '/financial-ingestion'
      path: '/financial-ingestion'
      fullPath: '/financial-ingestion'
      preLoaderRoute: typeof FinancialIngestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory-control': {
      id: '/inventory-control'
      path: '/inventory-control'
      fullPath: '/inventory-control'
      preLoaderRoute: typeof InventoryControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landowners-investment': {
      id: '/landowners-investment'
      path: '/landowners-investment'
      fullPath: '/landowners-investment'
      preLoaderRoute: typeof LandownersInvestmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-upload-studio': {
      id: '/media-upload-studio'
      path: '/media-upload-studio'
      fullPath: '/media-upload-studio'
      preLoaderRoute: typeof MediaUploadStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pmc-scope': {
      id: '/pmc-scope'
      path: '/pmc-scope'
      fullPath: '/pmc-scope'
      preLoaderRoute: typeof PmcScopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/po-create': {
      id: '/po-create'
      path: '/po-create'
      fullPath: '/po-create'
      preLoaderRoute: typeof PoCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pour-cards': {
      id: '/pour-cards'
      path: '/pour-cards'
      fullPath: '/pour-cards'
      preLoaderRoute: typeof PourCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-intelligence': {
      id: '/price-intelligence'
      path: '/price-intelligence'
      fullPath: '/price-intelligence'
      preLoaderRoute: typeof PriceIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-controls': {
      id: '/project-controls'
      path: '/project-controls'
      fullPath: '/project-controls'
      preLoaderRoute: typeof ProjectControlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects-setup': {
      id: '/projects-setup'
      path: '/projects-setup'
      fullPath: '/projects-setup'
      preLoaderRoute: typeof ProjectsSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders': {
      id: '/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchasing-center': {
      id: '/purchasing-center'
      path: '/purchasing-center'
      fullPath: '/purchasing-center'
      preLoaderRoute: typeof PurchasingCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-inspection': {
      id: '/qa-inspection'
      path: '/qa-inspection'
      fullPath: '/qa-inspection'
      preLoaderRoute: typeof QaInspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles-access': {
      id: '/roles-access'
      path: '/roles-access'
      fullPath: '/roles-access'
      preLoaderRoute: typeof RolesAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scope-brief': {
      id: '/scope-brief'
      path: '/scope-brief'
      fullPath: '/scope-brief'
      preLoaderRoute: typeof ScopeBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-execution': {
      id: '/site-execution'
      path: '/site-execution'
      fullPath: '/site-execution'
      preLoaderRoute: typeof SiteExecutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-media': {
      id: '/site-media'
      path: '/site-media'
      fullPath: '/site-media'
      preLoaderRoute: typeof SiteMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-directory': {
      id: '/system-directory'
      path: '/system-directory'
      fullPath: '/system-directory'
      preLoaderRoute: typeof SystemDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tender-comparison': {
      id: '/tender-comparison'
      path: '/tender-comparison'
      fullPath: '/tender-comparison'
      preLoaderRoute: typeof TenderComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-directory': {
      id: '/vendor-directory'
      path: '/vendor-directory'
      fullPath: '/vendor-directory'
      preLoaderRoute: typeof VendorDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-lifecycle': {
      id: '/vendor-lifecycle'
      path: '/vendor-lifecycle'
      fullPath: '/vendor-lifecycle'
      preLoaderRoute: typeof VendorLifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/': {
      id: '/ai/'
      path: '/ai'
      fullPath: '/ai/'
      preLoaderRoute: typeof AiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/$threadId': {
      id: '/ai/$threadId'
      path: '/ai/$threadId'
      fullPath: '/ai/$threadId'
      preLoaderRoute: typeof AiThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiProgrammeRoute: AiProgrammeRoute,
  BillingExpenditureRoute: BillingExpenditureRoute,
  BillsPaymentsRoute: BillsPaymentsRoute,
  BoqRoute: BoqRoute,
  BoqEngineRoute: BoqEngineRoute,
  BoqUploadRoute: BoqUploadRoute,
  BrandBenchmarkRoute: BrandBenchmarkRoute,
  CapitalLedgerRoute: CapitalLedgerRoute,
  CommandOperationsRoute: CommandOperationsRoute,
  ContractorsLabourRoute: ContractorsLabourRoute,
  DashboardRoute: DashboardRoute,
  DrawingDecipherRoute: DrawingDecipherRoute,
  ExecutionManualRoute: ExecutionManualRoute,
  FieldConsoleRoute: FieldConsoleRoute,
  FinancialForecastRoute: FinancialForecastRoute,
  FinancialIngestionRoute: FinancialIngestionRoute,
  InventoryControlRoute: InventoryControlRoute,
  LandownersInvestmentRoute: LandownersInvestmentRoute,
  MediaUploadStudioRoute: MediaUploadStudioRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  PmcScopeRoute: PmcScopeRoute,
  PoCreateRoute: PoCreateRoute,
  PourCardsRoute: PourCardsRoute,
  PriceIntelligenceRoute: PriceIntelligenceRoute,
  ProcurementRoute: ProcurementRoute,
  ProjectControlsRoute: ProjectControlsRoute,
  ProjectsRoute: ProjectsRoute,
  ProjectsSetupRoute: ProjectsSetupRoute,
  PurchaseOrdersRoute: PurchaseOrdersRoute,
  PurchasingCenterRoute: PurchasingCenterRoute,
  QaRoute: QaRoute,
  QaInspectionRoute: QaInspectionRoute,
  RolesAccessRoute: RolesAccessRoute,
  ScopeBriefRoute: ScopeBriefRoute,
  SiteExecutionRoute: SiteExecutionRoute,
  SiteMediaRoute: SiteMediaRoute,
  SystemDirectoryRoute: SystemDirectoryRoute,
  TenderComparisonRoute: TenderComparisonRoute,
  VendorDirectoryRoute: VendorDirectoryRoute,
  VendorLifecycleRoute: VendorLifecycleRoute,
  AiThreadIdRoute: AiThreadIdRoute,
  ApiChatRoute: ApiChatRoute,
  AiIndexRoute: AiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
